config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'user', to: "users#show", as: :user_root
  root "welcome#index"
  resources :users, only: [:show] 
  get 'all_expenses', to: 'expenses#all_expenses'
  get 'all_external_expenses', to: 'expenses#all_external_expenses'
  get 'all_groups', to: 'groups#index'
  resources :groups, except: [:index]
  resources :expenses, except: [:index]
  resources :expense_groups, only: [:create, :destroy]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :expense_groups, dependent: :destroy
  has_many :groups, through: :expense_groups, dependent: :destroy

  validates :name, presence: true
  validates :amount, presence: true, numericality: { only_float: true }
  validates :author_id, presence: true

  scope :created_by, ->(user) { where(author_id: user.id) }
  scope :ungrouped, -> { where.not(id: ExpenseGroup.where(expense_id: ids).pluck(:expense_id)) }
  scope :grouped, -> { where(id: ExpenseGroup.where(expense_id: ids).pluck(:expense_id)) }
  scope :sum_expenses, ->(ex) { ex.pluck(:amount).sum }
end

app/models/expense_group.rb
class ExpenseGroup < ApplicationRecord
  belongs_to :expense
  belongs_to :group
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :expense_groups, dependent: :destroy
  has_many :expenses, through: :expense_groups
  belongs_to :user
  has_one_attached :main_image

  validates :name, uniqueness: { scope: :user_id }, presence: true
  validate :acceptable_image

  scope :total, ->(g) { g.expenses.sum(:amount) }
  scope :order_alpha, -> { order('LOWER(name)') }

  def acceptable_image
    return unless main_image.attached?

    errors.add(:main_image, 'is too big') unless main_image.byte_size <= 1.megabyte

    acceptable_types = ['image/jpeg', 'image/png']
    errors.add(:main_image, 'must be a JPEG or PNG') unless acceptable_types.include?(main_image.content_type)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, presence: true

  has_many :expenses, class_name: 'Expense', foreign_key: 'author_id', dependent: :destroy
  has_many :groups, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/expense_groups_controller.rb
class ExpenseGroupsController < ApplicationController
  before_action :set_group
  before_action :set_expense

  def create
    ExpenseGroup.create(expense_id: @expense.id, group_id: @group.id)
    flash[:notice] = "Expense #{@expense.name} was successfully added to #{@group.name}"
    redirect_to @group
  end

  def destroy
    expense_group = ExpenseGroup.where(expense_id: @expense.id, group_id: @group.id).first
    expense_group.destroy
    flash[:notice] = "#{@expense.name} was successfully removed from #{@group.name}"
    redirect_to @group
  end

  private

  def set_expense
    @expense = Expense.find(params[:expense])
  end

  def set_group
    @group = Group.find(params[:group])
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_groups, only: %i[new edit]
  before_action :set_expense, only: %i[edit update destroy show]

  def all_expenses
    @expenses = current_user.expenses.order(created_at: :desc)
    @total = Expense.sum_expenses(@expenses)
  end

  def all_external_expenses
    @expenses = Expense.ungrouped.created_by(current_user).order(created_at: :desc)
    @total = Expense.sum_expenses(@expenses)
  end

  def show
    @groups = @expense.groups
  end

  def new
    @expense = Expense.new
  end

  def create
    @expense = current_user.expenses.build(expense_params)
    if @expense.save
      flash[:notice] = 'Expense was created successfully'
      redirect_to all_expenses_path
    else
      set_groups
      render 'new'
    end
  end

  def edit; end

  def update
    if @expense.update(expense_params)
      flash[:notice] = 'Expense was successfully updated'
      redirect_to all_expenses_path
    else
      render 'edit'
    end
  end

  def destroy
    @expense.destroy
    flash[:alert] = 'Expense deleted'
    redirect_to all_expenses_path
  end

  private

  def expense_params
    params.require(:expense).permit(:name, :amount, group_ids: [])
  end

  def set_groups
    @groups = current_user.groups
  end

  def set_expense
    @expense = Expense.find(params[:id])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]
  def index
    @groups = current_user.groups.order_alpha
    expenses = Expense.grouped.created_by(current_user)
    @total = Expense.sum_expenses(expenses)
  end

  def show
    @grouped = @group.expenses.order(created_at: :desc)
    @total = Group.total(@group)
    @ungrouped = Expense.ungrouped.created_by(current_user).last(5).reverse
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.build(group_params)
    if @group.save
      flash[:notice] = 'Group was created successfully'
      redirect_to @group
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @group.update(group_params)
      flash[:notice] = 'Group was successfully updated'
      redirect_to @group
    else
      render 'edit'
    end
  end

  def destroy
    @group.destroy
    redirect_to all_groups_path
  end

  private

  def group_params
    params.require(:group).permit(:name, :main_image)
  end

  def set_group
    @group = Group.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @grand_total = current_user.expenses.sum(:amount)
    @groups = current_user.groups
    @ungrouped = current_user.expenses.ungrouped
    @total = Expense.sum_expenses(@ungrouped)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include ActionView::Helpers::NumberHelper
  def toastr_flash
    flash.each_with_object([]) do |(type, message), flash_messages|
      type = 'success' if type == 'notice'
      type = 'error' if type == 'alert'
      text = "<script>toastr.#{type}('#{message}', '', { closeButton: true, progressBar: true })</script>"
      flash_messages << text.html_safe if message
    end.join("\n").html_safe
  end
end

app/helpers/author_helper.rb
module AuthorHelper
  def author_of_expense(expense, obj)
    "by #{expense.author.username}," if obj == @grouped
  end
end

app/helpers/expense_buttons_helper.rb
module ExpenseButtonsHelper
  def show_buttons(obj, expense)
    if obj == @grouped
      button_to 'Remove', expense_group_path(expense: expense.id, group: @group.id), method: :delete,
                                                                                     data: { confirm: 'Are you sure?' },
                                                                                     class: 'button is-small is-block'
    elsif obj == @ungrouped
      button_to 'Add', expense_groups_path(expense: expense.id, group: @group.id), method: :post,
                                                                                   class: 'button is-small is-block'
    end
  end
end

app/helpers/image_helper.rb
module ImageHelper
  def group_image(group_id, options = {})
    group = Group.find(group_id)
    if group.main_image.attached?
      image_tag(group.main_image.variant(resize_to_limit: [150, nil]), options)
    else
      image_tag('default_group_image.png')
    end
  end

  def expense_image(expense_id, options = {})
    expense = Expense.find(expense_id)
    group = expense.groups.first
    return group_image(group.id, options) unless group.nil?

    image_tag('default_group_image.png')
  end

  def gravatar_for(user, options = {})
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=200"
    image_tag(gravatar_url, options)
  end
end

app/views/application/_navigation.html.erb
<div class="hero-head">
  <nav class="navbar is-fixed-top is-primary" role="navigation" aria-label="main navigation">
    <div class="container">
      <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
          <%= image_tag("logo.png", alt: "HomeExpensesTracker", class: "logo-img") %>
        <% end %>

        <% if user_signed_in? %>
          <%= link_to "#{current_user.username}", user_path(current_user), class: "navbar-item" %>
        <% end %>
    
        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navMenu" onclick="toggleBurger()">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>
    
      <div id="navMenu" class="navbar-menu">
        <div class="navbar-start">
          <% if current_user %>
                
          <%= link_to 'New expense', new_expense_path, class: "navbar-item" %>
          
          <%= link_to 'Groups', all_groups_path, class: "navbar-item" %>
    
          <div class="navbar-item has-dropdown is-hoverable">
            <%= link_to 'Expenses', all_expenses_path, class: "navbar-link" %>
    
            <div class="navbar-dropdown">
              <%= link_to 'All Expenses', all_expenses_path, class: "navbar-item" %>
              <%= link_to 'All External Expenses', all_external_expenses_path, class: "navbar-item" %>
            </div>
          </div>
    
          <%= link_to "Edit Profile", edit_user_registration_path, class: "navbar-item" %>
    
          <% end %>
        </div>
    
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="buttons">
              <% if !current_user %>
                <%= link_to "<strong>Sign up</strong>".html_safe, new_user_registration_path, class: "button is-primary" %>
                <%= link_to "Log in", new_user_session_path, class: "button is-light" %>
              <% else %>
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "button is-light" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </nav>
</div>

<script>
function toggleBurger() {
  var burger = $(".burger");
  var menu = $(".navbar-menu");
  burger.toggleClass("is-active");
  menu.toggleClass("is-active");
}

</script>

app/views/expenses/_expense.html.erb
<div class="columns is-multiline">
  <% obj.each do |expense| %>
    <div class="column is-one-quarter expense-column">
      <div class="box mt-0">
        <article class="media">
          <figure class="media-left ml-0 mr-4 mb-0 expense-logo">
              <%= expense_image(expense.id) %>
          </figure>
          <div class="media-content">
            <div class="content">
              <p>
                <%= link_to expense.name, expense_path(expense) %> <br>
                <time datetime="2016-1-1" class="has-text-weight-light is-italic">Created <%= author_of_expense(expense, obj) %> <%= time_ago_in_words(expense.created_at)%> ago</time>
                <%= show_buttons(obj, expense) %> 
              </p>
            </div>
          </div>
          <div class="media-right">
            <p class="subtitle"><%= number_to_currency(expense.amount) %></p>
          </div>
        </article>
      </div>
    </div>
  <% end %>
</div>

app/views/expenses/_form.html.erb
<%= render 'shared/errors', obj: @expense %>
<%= form_with(model: @expense, local: true) do |f| %>
  <div class="field">
    <%= f.label :name, class: "label" %> 
    <div class="control">
      <%= f.text_field :name, class: "input", placeholder: "e.g Netflix" %>
    </div>
  </div>
  <div class="field">
    <%= f.label :amount, class: "label" %> 
    <div class="control">
      <%= f.text_field :amount, class: "input", placeholder: "e.g 15.99 " %>
    </div>
  </div>
  <div class="control">
      <%= f.label "Group(s)", class: "label" %>
      <p class="help">Select which group(s) this expense belong to (can be blank) or 
                      <%= link_to "Create a new group", new_group_path %> </p>
      <%= f.collection_check_boxes(:group_ids, @groups, :id, :name) do |b|  %>
        <div>
          <%= b.check_box %>
          <%= b.label %>
        </div>
      <% end %>
  </div>
  <%= f.submit "Submit", class: "button is-success mt-2" %>
<% end %>

<div class="mt-3"><%= link_to "Back", :back %></div>

app/views/expenses/all_expenses.html.erb
<h2>All Expenses</h2>

<%= render 'shared/add_new_link'%>

<%= render 'shared/total' %>

<%= render 'expense', obj: @expenses %>

app/views/expenses/all_external_expenses.html.erb
<h2>All External Expenses</h2>

<%= render 'shared/add_new_link'%>

<%= render 'shared/total' %>

<%= render 'expense', obj: @expenses %>

app/views/expenses/edit.html.erb
<h2>Edit expense</h2>

<%= render 'form' %>

app/views/expenses/new.html.erb
<h2>Create a new Expense</h2>

<%= render 'form' %>

app/views/expenses/show.html.erb
<div class="box mt-0">
  <article class="media">
    <figure class="media-left ml-0 mr-4 mb-0 expense-logo">
        <%= expense_image(@expense.id) %>
    </figure>
    <div class="media-content">
      <div class="content">
        <p class="is-size-5	has-text-success">
          <%= @expense.name %>
          <% @groups.each do |group| %>
            <span class="is-block has-text-black">Group(s): <%= link_to group.name, group_path(group), class: "is-success" %> </span>
          <% end %>
        </p>
        <div class="buttons">
          <button class="button is-primary is-small is-rounded"><%= link_to 'Edit', edit_expense_path(@expense), class: "has-text-white" %></button>
          <button class="button is-danger is-small is-rounded"><%= link_to 'Delete', expense_path(@expense), method: :delete, data: { confirm: "Are you sure?" }, class: "has-text-white"  %></button>
        </div>
          <time datetime="2016-1-1" class="has-text-weight-light is-italic">Created <%= time_ago_in_words(@expense.created_at)%> ago</time>        
      </div>
    </div>
    <div class="media-right">
      <p class="subtitle"><%= @expense.amount %></p>
    </div>    
  </article>
</div>

app/views/groups/_form.html.erb
<%= render 'shared/errors', obj: @group %>
<div class="field">
  <%= form_with(model: @group, local: true) do |f| %>
    <%= f.label :name, class: "label" %> 
    <div class="control">
      <%= f.text_field :name, class: "input", placeholder: "e.g Recurring Expenses" %>

      <div id="file-js-example" class="file has-name is-boxed mt-3">
        <label class="file-label">
        <%= f.file_field :main_image, class: "file-input", type: "file" %>
          <span class="file-cta">
            <span class="file-icon">
              <i class="fas fa-upload"></i>
            </span>
            <span class="file-label">
              Choose a file…
            </span>
          </span>
          <span class="file-name">
            No file chosen
          </span>
        </label>
      </div>
      <%= f.submit "Submit", class: "button is-success mt-3" %>
    </div>  
  <% end %>
</div>

<%= link_to "Back", :back %>

app/views/groups/_group.html.erb
<div class="columns is-multiline">
  <% @groups.each do |group| %>
    <div class="column is-one-quarter">
      <div class="box mt-0">
        <article class="media">
          <figure class="media-left ml-0 mr-4 mb-0 expense-logo">
              <%= group_image(group.id) %>
          </figure>
          <div class="media-content">
            <div class="content">
              <p>
                <%= link_to group.name.humanize, group_path(group) %> <br>
                <time datetime="2016-1-1" class="has-text-weight-light is-italic">Created <%= time_ago_in_words(group.created_at)%> ago</time>
              </p>
            </div>
          </div>
          <div class="media-right">
            <p class="subtitle"><%= number_to_currency(Group.total(group)) %></p>
          </div>
        </article>
      </div>
    </div>
  <% end %>
</div>

app/views/groups/edit.html.erb
<h2>Editing <%= @group.name %></h2>

<%= render 'form' %>

app/views/groups/index.html.erb
<h1>Your Groups</h1>

<button class="button is-primary is-rounded mb-5"><%= link_to 'New Group', new_group_path, class: "has-text-white" %></button>

<%= render 'shared/total' %>

<%= render 'group' %>

app/views/groups/new.html.erb
<h2>Create new Group</h2>

<%= render 'form' %>

app/views/groups/show.html.erb
<div class="is-flex mb-2 group-head-container">
  <div>
    <h2><%= @group.name %></h2>
  
    <div class="buttons">
      <button class="button is-primary is-rounded"><%= link_to 'Edit Group', edit_group_path(@group), class: "has-text-white" %></button>
      <button class="button is-danger is-rounded"><%= link_to 'Delete Group', group_path(@group), method: :delete, class: "has-text-white",
                                                      data: { confirm: "Deleting this group will not delete the expenses in this group. Delete?" } %></button>
      </div>
      
  
  </div>
  <figure class="expense-logo is-pulled-right mt-0 mx-0 group-show-logo">
    <%= group_image(@group.id) %>
  </figure>
</div>

<%= render 'shared/total' %>

<%= render 'shared/add_new_link'%>

<%= render 'expenses/expense', obj: @grouped %>

<h3>Try adding some of these ungrouped expenses:</h3>

<%= render 'expenses/expense', obj: @ungrouped %>

app/views/layouts/_messages.html.erb
<% if alert %>
  <article class="message is-danger">
    <div class="message-body">
      <%= alert %>
      <button class="delete" aria-label="delete"></button>
    </div>
  </article>
<% end %>

<% if notice %>
  <article class="message is-success">
    <div class="message-body">
      <%= notice %>
      <button class="delete" aria-label="delete"></button>
    </div>
  </article>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HomeExpensesTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'navigation' %>
    <% unless params[:controller] == 'welcome' %>
      <section class="section">
        <div class="content mt-5">
        <%= render 'layouts/messages' %>
          <div class="container"><%= yield %></div>
          <%= toastr_flash %>
        </div>
      </section>
    <% end %>
  </body>
  <%= javascript_pack_tag 'file_name', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'delete_button', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'burger_toggler', 'data-turbolinks-track': 'reload' %>
</html>

app/views/shared/_add_new_link.html.erb
<nav class="navbar is-fixed-bottom is-primary add-new has-text-centered">
  <%= link_to 'Add new', new_expense_path, class: "add-new-link" %>
</nav>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <article class="message is-danger">
    <div class="message-header">
      <p class="mb-0">The following errors prevented the <%= obj.class.name.downcase %> from being saved</p>
      <button class="delete" aria-label="delete"></button>
    </div>
    <div class="message-body">
        <ul class="mt-0">
          <% obj.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    </div>
  </article>
<% end %>

app/views/shared/_total.html.erb
<div class="box mt-0 total">
  Total: <div class="is-pulled-right"><%= number_to_currency(@total) %></div>
</div>
<hr>

app/views/users/_summary.html.erb
<table class="table is-hoverable">
  <thead>
    <tr>
      <th><abbr title="Position"><%= link_to "Group", all_groups_path %></abbr></th>
      <th>Total</th>
    </tr>
  </thead>
  <tfoot>
    <tr>
      <th><abbr title="Position"><%= link_to "All Expenses", all_expenses_path %></abbr></th>
      <th><%= number_to_currency(@grand_total) %></th>
    </tr>
  </tfoot>
  <tbody>  
    <% @groups.each do |g| %>
    <tr>
      <th><%= link_to g.name, group_path(g) %> </th>
      <td><%= number_to_currency(Group.total(g)) %></strong>
    </tr>
    <% end %>
    <tr>
      <th><%= link_to"External Expenses", all_external_expenses_path %></th>
      <td><%= number_to_currency(@total)  %></td>
    </tr>
  </tbody>
</table>

app/views/users/show.html.erb
<div class="has-text-centered">
  <figure class="image is-128x128 is-inline-block mb-0"><%= gravatar_for current_user %></figure>
  <h2 class="title is-2 has-text-primary">Welcome <%= current_user.username %> </h2>
  <h3 class="title is-3 has-text-primary">Summary</h3>
</div>


<%= render 'summary' %>

app/views/welcome/_navigation.html.erb
<section class="hero is-primary is-medium is-bold">
  <div class="hero-head">
    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="container">
        <div class="navbar-brand">
          <%= link_to root_path, class: "navbar-item" do %>
            <%= image_tag("logo.png", alt: "HomeExpensesTracker", class: "logo-img") %>
          <% end %>
          
          <% if user_signed_in? %>
            <%= link_to "#{current_user.username}", user_path(current_user), class: "navbar-item" %>
          <% end %>

      
          <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navMenu" onclick="toggleBurger()">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>
        
        <div id="navMenu" class="navbar-menu">
          <div class="navbar-start">
            <% if current_user %>              
      
            <%= link_to 'New expense', new_expense_path, class: "navbar-item" %>
            
            <%= link_to 'Groups', all_groups_path, class: "navbar-item" %>
      
            <div class="navbar-item has-dropdown is-hoverable">
              <%= link_to 'Expenses', all_expenses_path, class: "navbar-link" %>
      
              <div class="navbar-dropdown">
                <%= link_to 'All Expenses', all_expenses_path, class: "navbar-item" %>
                <%= link_to 'All External Expenses', all_external_expenses_path, class: "navbar-item" %>
              </div>
            </div>
      
            <%= link_to "Edit Profile", edit_user_registration_path, class: "navbar-item" %>
      
            <% end %>
          </div>
      
          <div class="navbar-end">
            <div class="navbar-item">
              <div class="buttons">
                <% if !current_user %>
                  <%= link_to "<strong>Sign up</strong>".html_safe, new_user_registration_path, class: "button is-primary" %>
                  <%= link_to "Log in", new_user_session_path, class: "button is-light" %>
                <% else %>
                  <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "button is-light" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </nav>
  </div>
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="title">
      Welcome to the Home Expenses Tracker
      </h1>
      <h2 class="subtitle">
      Track all your expense so you can take back control of your money!
      </h2>
      <% if user_signed_in? %>
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "button is-light" %>
      <% else %>
        <%= link_to "<strong>Sign up now!</strong>".html_safe, new_user_registration_path, class: "button is-success is-large" %> <br>
        <p class="tag or">OR</p> <br>
        <%= link_to "Log in", new_user_session_path, class: "button is-primary is-large" %>
      <% end %>
    </div>
  </div>
</section>

<script>
function toggleBurger() {
  var burger = $(".burger");
  var menu = $(".navbar-menu");
  burger.toggleClass("is-active");
  menu.toggleClass("is-active");
}
</script>